import type {
  ClockParams,
  CaptureClockParams,
  InputPathParams,
  OutputPathParams,
  FPGADeviceParams,
  ClockTopology,
  EdgeConfig,
  SourceSyncParams,
} from '../types/timing.ts';

/**
 * Generate Xilinx XDC (SDC-compatible) timing constraints.
 */
export function generateXDC(
  clock: ClockParams,
  inputPath: InputPathParams,
  outputPath: OutputPathParams,
  fpga: FPGADeviceParams,
  topology: ClockTopology,
  edgeConfig: EdgeConfig,
  sourceSync?: SourceSyncParams,
  captureClock?: CaptureClockParams,
): string {
  const lines: string[] = [
    `# FPGA Timing Constraints (XDC / SDC)`,
    `# Generated by TimingSim`,
    `# Topology: ${topology === 'system_sync' ? 'System Synchronous' : 'Source Synchronous'}`,
    `# Edge: Launch=${edgeConfig.launchEdge}, Capture=${edgeConfig.captureEdge}`,
    `# Jitter: input=${fmt(clock.inputJitter)}ns, system=${fmt(clock.systemJitter)}ns, uncertainty=${fmt(clock.uncertainty)}ns`,
    ``,
    `# Launch clock definition`,
    `create_clock -period ${fmt(clock.period)} -name ${clock.portName} [get_ports ${clock.portName}]`,
    `set_input_jitter [get_clocks -of_objects [get_ports ${clock.portName}]] ${fmt(clock.inputJitter)}`,
    `set_system_jitter ${fmt(clock.systemJitter)}`,
    `set_clock_uncertainty ${fmt(clock.uncertainty)} [get_clocks ${clock.portName}]`,
  ];

  // Independent capture clock
  if (captureClock) {
    lines.push(``);
    lines.push(`# Capture clock definition (independent)`);
    lines.push(`create_clock -period ${fmt(captureClock.period)} -name ${captureClock.portName} [get_ports ${captureClock.portName}]`);
    lines.push(`set_clock_uncertainty ${fmt(clock.uncertainty)} -from [get_clocks ${clock.portName}] -to [get_clocks ${captureClock.portName}]`);
    lines.push(`set_clock_uncertainty ${fmt(clock.uncertainty)} -from [get_clocks ${captureClock.portName}] -to [get_clocks ${clock.portName}]`);
  }

  // Source sync: create forwarded clock definition
  if (topology === 'source_sync' && sourceSync) {
    lines.push(``);
    lines.push(`# Forwarded clock from source device`);
    lines.push(`create_clock -period ${fmt(clock.period)} -name ${sourceSync.fwdClockPortName} [get_ports ${sourceSync.fwdClockPortName}]`);
    lines.push(`set_clock_uncertainty ${fmt(clock.uncertainty)} -from [get_clocks ${clock.portName}] -to [get_clocks ${sourceSync.fwdClockPortName}]`);
    lines.push(`set_clock_uncertainty ${fmt(clock.uncertainty)} -from [get_clocks ${sourceSync.fwdClockPortName}] -to [get_clocks ${clock.portName}]`);
  }

  const captureFallFlag = edgeConfig.captureEdge === 'falling' ? ' -clock_fall' : '';
  const skew = clock.skew;
  const inputClockRef = (topology === 'source_sync' && sourceSync)
    ? sourceSync.fwdClockPortName
    : captureClock ? captureClock.portName : clock.portName;
  const outputClockRef = (topology === 'source_sync' && sourceSync)
    ? sourceSync.fwdClockPortName
    : captureClock ? captureClock.portName : clock.portName;

  lines.push(``);
  lines.push(`# Input delay constraints`);
  lines.push(`# clock_skew offset applied to constraints = ${fmt(skew)} ns`);

  if (topology === 'source_sync' && sourceSync) {
    lines.push(`# Source Synchronous: referenced to forwarded clock (${inputClockRef})`);
    lines.push(`# input_delay = tco_source + routing_delay + clock_skew`);
    lines.push(`# Board delays are implicit — forwarded clock and data travel together on PCB`);
    lines.push(`set_input_delay -max ${fmt(inputPath.tcoSourceMax + inputPath.routingDelayMax + skew)}${captureFallFlag} -clock ${inputClockRef} [get_ports ${inputPath.portName}]`);
    lines.push(`set_input_delay -min ${fmt(inputPath.tcoSourceMin + inputPath.routingDelayMin + skew)}${captureFallFlag} -clock ${inputClockRef} [get_ports ${inputPath.portName}]`);
  } else {
    lines.push(`# System Synchronous: referenced to system clock (${clock.portName})`);
    lines.push(`# input_delay = tco_source + board_delay + routing_delay + clock_skew (source launch clock -> FPGA FF)`);
    lines.push(`set_input_delay -max ${fmt(inputPath.tcoSourceMax + inputPath.boardDelayMax + inputPath.routingDelayMax + skew)}${captureFallFlag} -clock ${clock.portName} [get_ports ${inputPath.portName}]`);
    lines.push(`set_input_delay -min ${fmt(inputPath.tcoSourceMin + inputPath.boardDelayMin + inputPath.routingDelayMin + skew)}${captureFallFlag} -clock ${clock.portName} [get_ports ${inputPath.portName}]`);
  }

  lines.push(``);
  lines.push(`# Output delay constraints`);
  if (topology === 'source_sync' && sourceSync) {
    lines.push(`# Source Synchronous: referenced to forwarded clock (${outputClockRef})`);
    lines.push(`# output_delay_max = board_delay_max + routing_delay_max + tsu_dest - fwd_clk_delay_min + clock_skew`);
    lines.push(`# output_delay_min = board_delay_min + routing_delay_min - th_dest - fwd_clk_delay_max + clock_skew`);
    lines.push(`set_output_delay -max ${fmt(outputPath.boardDelayMax + outputPath.routingDelayMax + outputPath.tsuDest - sourceSync.fwdClockBoardDelayMin + skew)}${captureFallFlag} -clock ${outputClockRef} [get_ports ${outputPath.portName}]`);
    lines.push(`set_output_delay -min ${fmt(outputPath.boardDelayMin + outputPath.routingDelayMin - outputPath.thDest - sourceSync.fwdClockBoardDelayMax + skew)}${captureFallFlag} -clock ${outputClockRef} [get_ports ${outputPath.portName}]`);
  } else {
    lines.push(`# Data path: launch FF -> routing_delay -> FPGA pin -> board_delay -> destination FF`);
    lines.push(`# output_delay_max = board_delay_max + routing_delay_max + tsu_dest + clock_skew`);
    lines.push(`# output_delay_min = board_delay_min + routing_delay_min - th_dest + clock_skew`);
    lines.push(`set_output_delay -max ${fmt(outputPath.boardDelayMax + outputPath.routingDelayMax + outputPath.tsuDest + skew)}${captureFallFlag} -clock ${clock.portName} [get_ports ${outputPath.portName}]`);
    lines.push(`set_output_delay -min ${fmt(outputPath.boardDelayMin + outputPath.routingDelayMin - outputPath.thDest + skew)}${captureFallFlag} -clock ${clock.portName} [get_ports ${outputPath.portName}]`);
  }

  lines.push(``);
  lines.push(`# FPGA device parameters (for reference)`);
  lines.push(`# tsu_FPGA = ${fmt(fpga.tsu)} ns`);
  lines.push(`# th_FPGA  = ${fmt(fpga.th)} ns`);
  lines.push(`# tco_max  = ${fmt(fpga.tcoMax)} ns`);
  lines.push(`# tco_min  = ${fmt(fpga.tcoMin)} ns`);

  if (topology === 'source_sync' && sourceSync) {
    lines.push(``);
    lines.push(`# Source sync forwarded clock board delay (for reference)`);
    lines.push(`# fwd_clk_board_delay_max = ${fmt(sourceSync.fwdClockBoardDelayMax)} ns`);
    lines.push(`# fwd_clk_board_delay_min = ${fmt(sourceSync.fwdClockBoardDelayMin)} ns`);
  }

  return lines.join('\n');
}

function fmt(val: number): string {
  return val.toFixed(3);
}
